[project]
name = "final-leaf-addon"
authors = ["Leafy Web3 Team"]
description = "Dynamic step tracking and reward distribution smart contract"
telemetry = false
requirements = []
[contracts.leaf-stride]
path = "contracts/leaf-stride.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
